language: python
python:
  - "2.7"
install: 
  - pip install tox
  - npm install bower -g
  - npm install -g node-sass
script:
  - tox
before_deploy:
  - npm install netlify-cli -g
deploy:
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
      secret_access_key: $AWS_SECRET_KEY
      bucket: reformedconfessions.com
      region: us-east-1
      skip_cleanup: true
      local-dir: flask_application/build
      acl: public_read
      default_text_charset: 'utf-8'
      detect_encoding: true
      on:
        branch: master
notifications:
  email:
    recipients:
      - tdhopper@gmail.com
    on_success: change
    on_failure: always
