language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script: py.test
notifications:
  email:
    recipients:
      - tdhopper@gmail.com
    on_success: change
    on_failure: always
