sudo: false
language: python
python:
  - "3.7"
install: pip install tox-travis
script:
  - echo 1
before_deploy:
  - tox -e lambda
deploy:
  provider: lambda
  function_name: "westminster-daily-tweet"
  region: "us-east-1"
  runtime: "python3.7"
  handler_name: "tweet"
  module_name: "update"
  role: "arn:aws:iam::212595366334:role/lambda_basic_execution"
  zip: lambda
  timeout: 30
  on:
    branch: master
