language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script:
  - npm install
  - npm install -g bower
  - make flask_application/bower_components
  - py.test --verbose --full-trace --ignore=node_modules
  - make build
before_deploy:
  - npm install netlify-cli -g
deploy:
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
      secret_access_key: $AWS_SECRET_KEY
      bucket: reformedconfessions.com
      region: us-east-1
      skip_cleanup: true
      local-dir: flask_application/build
      acl: public_read
      default_text_charset: 'utf-8'
      detect_encoding: true
      on:
        branch: master
    - provider: script
      skip_cleanup: true
      script: netlify deploy --prod --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID --dir ./flask_application/build/
      on:
        netlify
notifications:
  email:
    recipients:
      - tdhopper@gmail.com
    on_success: change
    on_failure: always
