pkill python; fab build_images:1
pkill python; fab build_images:2
pkill python; fab build_images:3
pkill python; fab build_images:4
pkill python; fab build_images:5
pkill python; fab build_images:6
pkill python; fab build_images:7
pkill python; fab build_images:8
pkill python; fab build_images:9
pkill python; fab build_images:10
pkill python; fab build_images:11
pkill python; fab build_images:12