[build]
  base    = "."
  publish = "./build"
  command = "python -V && npm install --quiet -g node-sass@4.13.0 & python -m pip install --quiet tox && make all"

[[redirects]]
  from = "/static/images/docs/*"
  to = "https://s3.amazonaws.com/www.reformedconfessions.com/westminster-daily/static/images/docs/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/"
  to = "/westminster-daily/"
  status = 200
  force = true

[[redirects]]
  from = "/about"
  to = "/westminster-daily/about"
  status = 200
  force = true
